version: '3.0'

services:
  dbpostgres:
    image: bitnami/postgresql:latest
    container_name: jupiter
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=jupiter
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local

